export const SHIPPING_CREATE_REQUEST='SHIPPING_CREATE_REQUEST';
export const SHIPPING_CREATE_SUCCESS='SHIPPING_CREATE_SUCCESS';
export const SHIPPING_CREATE_FAIL='SHIPPING_CREATE_FAIL';
export const SHIPPING_CREATE_RESET='SHIPPING_CREATE_RESET';